// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.17.3
// source: pkg/enemy/enemy.proto

package enemy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Enemy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email       string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Rating      float32                `protobuf:"fixed32,4,opt,name=rating,proto3" json:"rating,omitempty"`
	LastUpdated *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=lastUpdated,proto3" json:"lastUpdated,omitempty"`
}

func (x *Enemy) Reset() {
	*x = Enemy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_enemy_enemy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Enemy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enemy) ProtoMessage() {}

func (x *Enemy) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_enemy_enemy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enemy.ProtoReflect.Descriptor instead.
func (*Enemy) Descriptor() ([]byte, []int) {
	return file_pkg_enemy_enemy_proto_rawDescGZIP(), []int{0}
}

func (x *Enemy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Enemy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Enemy) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Enemy) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Enemy) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type AddEnemyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email  string  `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Rating float32 `protobuf:"fixed32,3,opt,name=rating,proto3" json:"rating,omitempty"`
}

func (x *AddEnemyRequest) Reset() {
	*x = AddEnemyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_enemy_enemy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddEnemyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEnemyRequest) ProtoMessage() {}

func (x *AddEnemyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_enemy_enemy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEnemyRequest.ProtoReflect.Descriptor instead.
func (*AddEnemyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_enemy_enemy_proto_rawDescGZIP(), []int{1}
}

func (x *AddEnemyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddEnemyRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AddEnemyRequest) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type AddEnemyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enemy *Enemy `protobuf:"bytes,1,opt,name=enemy,proto3" json:"enemy,omitempty"`
}

func (x *AddEnemyResponse) Reset() {
	*x = AddEnemyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_enemy_enemy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddEnemyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEnemyResponse) ProtoMessage() {}

func (x *AddEnemyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_enemy_enemy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEnemyResponse.ProtoReflect.Descriptor instead.
func (*AddEnemyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_enemy_enemy_proto_rawDescGZIP(), []int{2}
}

func (x *AddEnemyResponse) GetEnemy() *Enemy {
	if x != nil {
		return x.Enemy
	}
	return nil
}

type GetEnemyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetEnemyRequest) Reset() {
	*x = GetEnemyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_enemy_enemy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEnemyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnemyRequest) ProtoMessage() {}

func (x *GetEnemyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_enemy_enemy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnemyRequest.ProtoReflect.Descriptor instead.
func (*GetEnemyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_enemy_enemy_proto_rawDescGZIP(), []int{3}
}

func (x *GetEnemyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEnemyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enemy *Enemy `protobuf:"bytes,1,opt,name=enemy,proto3" json:"enemy,omitempty"`
}

func (x *GetEnemyResponse) Reset() {
	*x = GetEnemyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_enemy_enemy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEnemyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnemyResponse) ProtoMessage() {}

func (x *GetEnemyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_enemy_enemy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnemyResponse.ProtoReflect.Descriptor instead.
func (*GetEnemyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_enemy_enemy_proto_rawDescGZIP(), []int{4}
}

func (x *GetEnemyResponse) GetEnemy() *Enemy {
	if x != nil {
		return x.Enemy
	}
	return nil
}

type UpdateEnemyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email  string  `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Rating float32 `protobuf:"fixed32,4,opt,name=rating,proto3" json:"rating,omitempty"`
}

func (x *UpdateEnemyRequest) Reset() {
	*x = UpdateEnemyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_enemy_enemy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEnemyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEnemyRequest) ProtoMessage() {}

func (x *UpdateEnemyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_enemy_enemy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEnemyRequest.ProtoReflect.Descriptor instead.
func (*UpdateEnemyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_enemy_enemy_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateEnemyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEnemyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateEnemyRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateEnemyRequest) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type UpdateEnemyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enemy *Enemy `protobuf:"bytes,1,opt,name=enemy,proto3" json:"enemy,omitempty"`
}

func (x *UpdateEnemyResponse) Reset() {
	*x = UpdateEnemyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_enemy_enemy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEnemyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEnemyResponse) ProtoMessage() {}

func (x *UpdateEnemyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_enemy_enemy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEnemyResponse.ProtoReflect.Descriptor instead.
func (*UpdateEnemyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_enemy_enemy_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateEnemyResponse) GetEnemy() *Enemy {
	if x != nil {
		return x.Enemy
	}
	return nil
}

type ListEnemiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListEnemiesRequest) Reset() {
	*x = ListEnemiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_enemy_enemy_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEnemiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnemiesRequest) ProtoMessage() {}

func (x *ListEnemiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_enemy_enemy_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnemiesRequest.ProtoReflect.Descriptor instead.
func (*ListEnemiesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_enemy_enemy_proto_rawDescGZIP(), []int{7}
}

type ListEnemiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enemies []*Enemy `protobuf:"bytes,1,rep,name=enemies,proto3" json:"enemies,omitempty"`
}

func (x *ListEnemiesResponse) Reset() {
	*x = ListEnemiesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_enemy_enemy_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEnemiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnemiesResponse) ProtoMessage() {}

func (x *ListEnemiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_enemy_enemy_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnemiesResponse.ProtoReflect.Descriptor instead.
func (*ListEnemiesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_enemy_enemy_proto_rawDescGZIP(), []int{8}
}

func (x *ListEnemiesResponse) GetEnemies() []*Enemy {
	if x != nil {
		return x.Enemies
	}
	return nil
}

var File_pkg_enemy_enemy_proto protoreflect.FileDescriptor

var file_pkg_enemy_enemy_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x65, 0x6e, 0x65, 0x6d, 0x79, 0x2f, 0x65, 0x6e, 0x65, 0x6d,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x65, 0x6e, 0x65, 0x6d, 0x79, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x97, 0x01, 0x0a, 0x05, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x3c, 0x0a, 0x0b, 0x6c,
	0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x6c, 0x61,
	0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x22, 0x53, 0x0a, 0x0f, 0x41, 0x64, 0x64,
	0x45, 0x6e, 0x65, 0x6d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x36,
	0x0a, 0x10, 0x41, 0x64, 0x64, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x65, 0x6e, 0x65, 0x6d, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x65, 0x6e, 0x65, 0x6d, 0x79, 0x2e, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x52,
	0x05, 0x65, 0x6e, 0x65, 0x6d, 0x79, 0x22, 0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x65,
	0x6d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x36, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x45, 0x6e, 0x65, 0x6d, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a,
	0x05, 0x65, 0x6e, 0x65, 0x6d, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x65,
	0x6e, 0x65, 0x6d, 0x79, 0x2e, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x52, 0x05, 0x65, 0x6e, 0x65, 0x6d,
	0x79, 0x22, 0x66, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x65, 0x6d, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x39, 0x0a, 0x13, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x22, 0x0a, 0x05, 0x65, 0x6e, 0x65, 0x6d, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x65, 0x6e, 0x65, 0x6d, 0x79, 0x2e, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x52, 0x05, 0x65,
	0x6e, 0x65, 0x6d, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x65, 0x6d,
	0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3d, 0x0a, 0x13, 0x4c, 0x69,
	0x73, 0x74, 0x45, 0x6e, 0x65, 0x6d, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x26, 0x0a, 0x07, 0x65, 0x6e, 0x65, 0x6d, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x65, 0x6e, 0x65, 0x6d, 0x79, 0x2e, 0x45, 0x6e, 0x65, 0x6d, 0x79,
	0x52, 0x07, 0x65, 0x6e, 0x65, 0x6d, 0x69, 0x65, 0x73, 0x32, 0x9c, 0x02, 0x0a, 0x0c, 0x45, 0x6e,
	0x65, 0x6d, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x08, 0x41, 0x64,
	0x64, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x12, 0x16, 0x2e, 0x65, 0x6e, 0x65, 0x6d, 0x79, 0x2e, 0x41,
	0x64, 0x64, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17,
	0x2e, 0x65, 0x6e, 0x65, 0x6d, 0x79, 0x2e, 0x41, 0x64, 0x64, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x08, 0x47, 0x65, 0x74,
	0x45, 0x6e, 0x65, 0x6d, 0x79, 0x12, 0x16, 0x2e, 0x65, 0x6e, 0x65, 0x6d, 0x79, 0x2e, 0x47, 0x65,
	0x74, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x65, 0x6e, 0x65, 0x6d, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x12, 0x19, 0x2e, 0x65, 0x6e, 0x65, 0x6d, 0x79, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x65, 0x6e, 0x65, 0x6d, 0x79, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x46, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x65, 0x6d, 0x69, 0x65, 0x73, 0x12,
	0x19, 0x2e, 0x65, 0x6e, 0x65, 0x6d, 0x79, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x65, 0x6d,
	0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x65, 0x6e, 0x65,
	0x6d, 0x79, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x65, 0x6d, 0x69, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x61, 0x72, 0x77, 0x65, 0x66, 0x2f, 0x72, 0x70,
	0x69, 0x2d, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x2d, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x65, 0x6e, 0x65, 0x6d, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_enemy_enemy_proto_rawDescOnce sync.Once
	file_pkg_enemy_enemy_proto_rawDescData = file_pkg_enemy_enemy_proto_rawDesc
)

func file_pkg_enemy_enemy_proto_rawDescGZIP() []byte {
	file_pkg_enemy_enemy_proto_rawDescOnce.Do(func() {
		file_pkg_enemy_enemy_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_enemy_enemy_proto_rawDescData)
	})
	return file_pkg_enemy_enemy_proto_rawDescData
}

var file_pkg_enemy_enemy_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_enemy_enemy_proto_goTypes = []interface{}{
	(*Enemy)(nil),                 // 0: enemy.Enemy
	(*AddEnemyRequest)(nil),       // 1: enemy.AddEnemyRequest
	(*AddEnemyResponse)(nil),      // 2: enemy.AddEnemyResponse
	(*GetEnemyRequest)(nil),       // 3: enemy.GetEnemyRequest
	(*GetEnemyResponse)(nil),      // 4: enemy.GetEnemyResponse
	(*UpdateEnemyRequest)(nil),    // 5: enemy.UpdateEnemyRequest
	(*UpdateEnemyResponse)(nil),   // 6: enemy.UpdateEnemyResponse
	(*ListEnemiesRequest)(nil),    // 7: enemy.ListEnemiesRequest
	(*ListEnemiesResponse)(nil),   // 8: enemy.ListEnemiesResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_pkg_enemy_enemy_proto_depIdxs = []int32{
	9, // 0: enemy.Enemy.lastUpdated:type_name -> google.protobuf.Timestamp
	0, // 1: enemy.AddEnemyResponse.enemy:type_name -> enemy.Enemy
	0, // 2: enemy.GetEnemyResponse.enemy:type_name -> enemy.Enemy
	0, // 3: enemy.UpdateEnemyResponse.enemy:type_name -> enemy.Enemy
	0, // 4: enemy.ListEnemiesResponse.enemies:type_name -> enemy.Enemy
	1, // 5: enemy.EnemyService.AddEnemy:input_type -> enemy.AddEnemyRequest
	3, // 6: enemy.EnemyService.GetEnemy:input_type -> enemy.GetEnemyRequest
	5, // 7: enemy.EnemyService.UpdateEnemy:input_type -> enemy.UpdateEnemyRequest
	7, // 8: enemy.EnemyService.ListEnemies:input_type -> enemy.ListEnemiesRequest
	2, // 9: enemy.EnemyService.AddEnemy:output_type -> enemy.AddEnemyResponse
	4, // 10: enemy.EnemyService.GetEnemy:output_type -> enemy.GetEnemyResponse
	6, // 11: enemy.EnemyService.UpdateEnemy:output_type -> enemy.UpdateEnemyResponse
	8, // 12: enemy.EnemyService.ListEnemies:output_type -> enemy.ListEnemiesResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_enemy_enemy_proto_init() }
func file_pkg_enemy_enemy_proto_init() {
	if File_pkg_enemy_enemy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_enemy_enemy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Enemy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_enemy_enemy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddEnemyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_enemy_enemy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddEnemyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_enemy_enemy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEnemyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_enemy_enemy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEnemyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_enemy_enemy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateEnemyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_enemy_enemy_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateEnemyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_enemy_enemy_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListEnemiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_enemy_enemy_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListEnemiesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_enemy_enemy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_enemy_enemy_proto_goTypes,
		DependencyIndexes: file_pkg_enemy_enemy_proto_depIdxs,
		MessageInfos:      file_pkg_enemy_enemy_proto_msgTypes,
	}.Build()
	File_pkg_enemy_enemy_proto = out.File
	file_pkg_enemy_enemy_proto_rawDesc = nil
	file_pkg_enemy_enemy_proto_goTypes = nil
	file_pkg_enemy_enemy_proto_depIdxs = nil
}
