// Code generated by sqlc. DO NOT EDIT.

package storage

import (
	"time"
)

type Enemy struct {
	ID          int32     `json:"id"`
	EnemyID     string    `json:"enemy_id"`
	FullName    string    `json:"full_name"`
	Email       string    `json:"email"`
	Rating      float32   `json:"rating"`
	LastUpdated time.Time `json:"last_updated"`
}
