version: "3.7"
services:
  my-test-app:
    image: ${IMAGE}
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=postgres
    ports:
      - 8080:8080
    networks:
      - enemyServiceNetwork
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - enemyServiceNetwork
networks:
  enemyServiceNetwork: {}
